<?php
/**
 * This file is part of Easygento_InstanceReminder for Magento.
 *
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Phuong LE <sony@menincode.com> <Menincode>
 * @category Easygento
 * @package Easygento_InstanceReminder
 */
?>
<?php /** @var Mage_Adminhtml_Block_Template $this */ ?>
<?php
/** @var Easygento_InstanceReminder_Helper_Data $_helper */
$_helper = Mage::helper('easygento_instancereminder');
?>
<?php if ($_helper->isEnabled()) : ?>
    <?php if ($_helper->isAdminLoginPage()): ?>
        <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('easygento/instancereminder/topbar.css') ?>" media="all"/>
    <?php endif; ?>
    <style>
        #easygento_ir {
            background: <?php echo $_helper->getColorByInstance() ?>;
        }
    </style>
    <div id="easygento_ir">
        <img id="easygento_ir_logo" src="<?php echo $this->getSkinUrl('images/easygento/logo.png') ?>" alt="Easygento">
        <span><?php echo $_helper->getInstanceName() ?></span>
    </div>
<?php endif; ?>